CREATE OR REPLACE PACKAGE PA_ADMINISTRADOR IS
  FUNCTION CO_Colores RETURN SYS_REFCURSOR;
  FUNCTION CO_ORdenes RETURN XMLTYPE;
  FUNCTION CO_Vendidos RETURN SYS_REFCURSOR;
END PA_ADMINISTRADOR;

CREATE OR REPLACE PACKAGE PA_CLIENTE IS
  FUNCTION CO_INFORMACION RETURN XMLTYPE;
END PA_CLIENTE;