/*Remover Ejecucion*/
REVOKE EXECUTE ON PA_PRESIDENTE FROM PRESIDENTE;
REVOKE EXECUTE ON PA_ORGANIZADOR FROM ORGANIZADOR;
REVOKE EXECUTE ON PA_TECNICO FROM TECNICO;
REVOKE EXECUTE ON PA_PDIMAYOR FROM PRESIDENTEDIMAYOR;
/*Remover Roles*/
DROP ROLE PRESIDENTE;
DROP ROLE ORGANIZADOR;
DROP ROLE TECNICO;
DROP ROLE PRESIDENTEDIMAYOR;
/*Borrar Paquetes*/
DROP PACKAGE PA_PRESIDENTE;
DROP PACKAGE PA_ORGANIZADOR;
DROP PACKAGE PA_TECNICO;
DROP PACKAGE PA_PDIMAYOR;
--alter session set "_oracle_script"=true;