/*Roles*/
CREATE ROLE PRESIDENTE;
CREATE ROLE ORGANIZADOR;
CREATE ROLE TECNICO;
CREATE ROLE PRESIDENTEDIMAYOR;
/*Garantizar Ejecucion*/
GRANT EXECUTE ON PA_PRESIDENTE TO PRESIDENTE;
GRANT EXECUTE ON PA_ORGANIZADOR TO ORGANIZADOR;
GRANT EXECUTE ON PA_TECNICO TO TECNICO;
GRANT EXECUTE ON PA_PDIMAYOR TO PRESIDENTEDIMAYOR;
