/*Remover Ejecucion*/
REVOKE EXECUTE ON PA_PRESIDENTE FROM PRESIDENTE;
REVOKE EXECUTE ON PA_ORGANIZADOR FROM ORGANIZADOR;
REVOKE EXECUTE ON PA_TECNICO FROM TECNICO;
REVOKE EXECUTE ON PA_PDIMAYOR FROM PRESIDENTEDIMAYOR;
/*Remover Roles*/
DROP ROLE PRESIDENTE;
DROP ROLE ORGANIZADOR;
DROP ROLE TECNICO;
DROP ROLE PRESIDENTEDIMAYOR;